;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	forward-sentence
	ido-hacks-execute-extended-command
	kill-region
	))

(setq mc/cmds-to-run-once
      '(
	dabbrev-completion
	magit-status
	))
