;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-to-word
        cljr-expand-let
        forward-sentence
        ido-hacks-execute-extended-command
        kill-region
        kill-sexp
        org-self-insert-command
        paredit-backward
        paredit-backward-up
        paredit-forward
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-kill-word
        paredit-kill
        paredit-open-round
        paredit-wrap-round
        save-some-buffers
        slime-autodoc-space
        wgrep-finish-edit
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        dabbrev-completion
        magit-status
        paredit-doublequote
        ))
